---
title: "Wikipedia Pageviews"
output: 
  flexdashboard::flex_dashboard:
    logo: "logo.png"
    orientation: rows
    vertical_layout: fill
    css: styles.css
    source_code: embed
    social: ["twitter", "facebook", "google-plus","linkedin", "pinterest"]
runtime: shiny    
---

```{r setup, warning= FALSE ,message = FALSE}

library(flexdashboard)
#library(shiny)
library(pageviews)
library(DT)
library(plotly)
library(stringr)
library(GuardianR)
library(httr)
library(rvest)
library(XML)
library(selectr)
library(feather)
library(tidyverse)

# pageViewsEn <- read_csv("data/pageViewsEn.csv") %>% 
#   data.frame()#  has attr otherwise

# fast and no ascii issues cf readr
pageViewsEn <- read_feather("pageViewsEn.feather")

exclude <- c("Main_Page","404.php", "Special:Search","Special:CreateAccount","Special:Book","Special:RecentChanges",
             "Special:RecentChanges","Special:Watchlist","Special:MobileMenu","Special:MobileOptions"
             ,"Special:RecentChangesLinked","Special:CiteThisPage","Special:LinkSearch","Special:WhatLinksHere","Special:MyTalk","Special:Log","Special:BookSources","Special:RecentChangesLinked/Portal:Contents")

urlBase <-"https://en.wikipedia.org/wiki/"


```


Home
===================================== 


Column {data-width=650}
-----------------------------------------------------------------------

### Compare one or more Wikipedia pages from mid 2015 to date. Stick to one for Guardian links and Wiki sidebar

```{r carpenrty, warning= FALSE ,message = FALSE}

# Input
textInput(inputId="articles",label="Start words with capital letter. Check wiki page for exact input, if required",placeholder = "e.g. George Michael,Glenn Frey")

# Only action when list complete
actionButton(inputId="go",label="Go")


data <- eventReactive(input$go,{

  # manipulate input as required for pageviews function
  vals <- str_trim(unlist(str_split(input$articles,",")))
  today <- paste0(str_replace_all(Sys.Date(),"-",""),"00")
 
  # Actual start date is from mid 2015
comp_pageviews <- article_pageviews(article = vals,
                                     start = "2015010100", end = today)
info=list(df=comp_pageviews,vals=vals)

   } )

```



```{r table, warning= FALSE ,message = FALSE}

# tabular output
output$wikitable <- DT::renderDataTable({
  req(data)
 
data()$df %>%
  group_by(article) %>%
  summarise(tot=sum(views),max=max(views),min=min(views),median=round(median(views),0),toppc=round(100*max/tot),maxdate=as.Date(date[which(views==max(views))]))%>%
  arrange(desc(median)) %>%
                         DT::datatable(class='compact stripe hover row-border order-column',rownames=FALSE,options= list(paging = FALSE, searching = FALSE,info=FALSE))
})

DT::dataTableOutput("wikitable")

```

### Daily hits on English version. Zoom as required. Click date for Guardian articles

```{r chart, warning= FALSE ,message = FALSE}
output$wikiplot <- renderPlotly({
  
   req(data)
  
data()$df %>% 
  plot_ly(x=~date, y=~log10(views), color=~article) %>% 
  add_lines(showlegend=FALSE) %>% 
  add_markers( text=~paste0("Views: ",views), key= ~article) %>% 
  layout(
    title="Daily Views of article(s) on English Wikipedia<br> (Hover for details)",
    xaxis=list(title=""),
    yaxis=list(title="Views (log10)")
  ) 
})
  plotlyOutput("wikiplot")

```


Column {data-width=350}
-----------------------------------------------------------------------


### Wikipedia Sidebar (first name entered) Links inoperable

```{r }


output$wikiCard <- renderUI({
  req(data())
  
  theName <- str_replace_all(data()$vals[1]," ","_")
  url <- paste0("http://en.wikipedia.org/wiki/",theName)
  test <- http_status(GET(url))
  
  if (test$category == "client error")
    return()

  vcard <- read_html(url) %>%
    html_nodes(".vcard")
  
  if (length(vcard) == 0)
    return()
  
  vcardInfo <- vcard[[1]]
  
  HTML(as(vcardInfo,"character"))
})

 uiOutput("wikiCard")

```



### Guardian Articles (Most Popular wiki selection only)

```{r articles, warning= FALSE ,message = FALSE}

# Needs more development
 output$guardianTable <- DT::renderDataTable({
   req(event_data("plotly_click"))
       d <- event_data("plotly_click")
     
    if (is.null(d)) {
      return()
    } else  {
  theDate <- d[["x"]]
 
  cN <- d[["curveNumber"]] # currently not utilized
  
    }
   

 
betterName <- str_trim(str_split(data()$vals[cN],"[(]")[[1]][1])  # caters for those wher has say more than 1


theName <- str_replace_all(betterName," ","+")
 #  encapsulate for exact name - otherwise will include undesired links
  theName <- paste0("%22",theName,"%22")
 

results <- get_guardian(
  theName,
  from.date = theDate,
  to.date = theDate,
  
  api.key = "3xzg2fk53jcdgaj5tbwqqhcz" # from vignette seems to work
)

link <- character()
  blankdf <- data.frame(link)
  
  ## work still required
if (nrow(results) == 1 | is.na(results$id[1])) {
  DT::datatable(
    blankdf,rownames = FALSE,escape = FALSE,options = list(
      paging = FALSE, searching = FALSE,info = FALSE
    )
  )
} else {
  results %>%
    mutate(link = paste0(
      "<a href=\"",webUrl,"\" target=\"_blank\">", webTitle,"</a>"
    )) %>%
    select(link) %>%
    DT::datatable(
      rownames = FALSE,escape = FALSE,options = list(
        paging = TRUE, searching = FALSE,info = FALSE, pageLength = 5
      )
    )
}



  
   
 })

DT::dataTableOutput("guardianTable")
```




Daily Top 1000
=====================================

Inputs {.sidebar data-width=400}
-------------------------------------

```{r}

includeMarkdown("info.md")
hr()
p()
p()
dateInput(inputId = "topTenDate", label="Change Date", value = Sys.Date()-1, min = "2015-07-01", max =  Sys.Date()-1,
  format = "yyyy-mm-dd", startview = "month", weekstart = 0,
  language = "en", width = NULL)

```


```{r}

tt <- reactive({

req(input$topTenDate)

todayTopThousand <- top_articles(start = as.Date(input$topTenDate)) %>% 
  filter(!article %in% exclude)
 

todayTopTen <- todayTopThousand %>% 
  select(article,views) %>%
  mutate(rank=min_rank(-views)) %>%
  head(10)


  vcardImage <- vector(mode = "character", length = 10)

for(i in seq_along(todayTopTen$article)) {
  
  topName <- todayTopTen$article[i]
  url <- paste0("http://en.wikipedia.org/wiki/",topName)
  test <- http_status(GET(url))
  
  temp <- read_html(url) %>%
    html_nodes(".vcard img") %>% 
    html_attr("src")
  
  vcardImage[i]<- ifelse(length(temp!=0),temp,"http://www.premiersoccerstats.com/noImage2.jpg")
  
}



info=list(vcardImage=vcardImage,todayTopTen=todayTopTen,todayTopThousand=todayTopThousand)
return(info)

})

```



---

```{r}
 

output$thousandTable <- DT::renderDataTable({
  
   req(tt())
  
tt()$todayTopThousand %>% 
  mutate(webUrl = paste0(urlBase,article)) %>% 
  
   mutate(link = paste0("<a href=\"", webUrl, "\" target=\"_blank\">", article, "</a>")) %>% 
  select(link,views) %>%
 DT::datatable(class='compact stripe hover row-border order-column',rownames=TRUE,
               escape = FALSE,options= list(paging = TRUE, searching = TRUE,info=FALSE))
})

DT::dataTableOutput("thousandTable")

```

<a id="blogLink" href="http://www.mytinyshinys.com/" >myTinyShinys Website</a>

Row 
-----------------------------------------------------------------------

### 1


```{r}

output$one <- renderUI({
 
  req(tt())
  
  txt <- str_replace_all(paste0(tt()$todayTopTen$article[1]," ",tt()$todayTopTen$views[1]," views"),"_"," ")
 
  list(h4(strong(txt)),
       img(src=tt()$vcardImage[1]))
})

uiOutput("one")


```

### 2


```{r}

output$two <- renderUI({
 
  req(tt())
  
 txt <- str_replace_all(paste0(tt()$todayTopTen$article[2]," ",tt()$todayTopTen$views[2]," views"),"_"," ")
 
  list(h4(strong(txt)),
       img(src=tt()$vcardImage[2]))
})




uiOutput("two")

```

### 3


```{r}

output$three <- renderUI({
 
  
  req(tt())
  
  txt <- str_replace_all(paste0(tt()$todayTopTen$article[3]," ",tt()$todayTopTen$views[3]," views"),"_"," ")
 
  list(h4(strong(txt)),
       img(src=tt()$vcardImage[3]))
})




uiOutput("three")

```

### 4


```{r}

output$four <- renderUI({
 
 
  req(tt())
  
  txt <- str_replace_all(paste0(tt()$todayTopTen$article[4]," ",tt()$todayTopTen$views[4]," views"),"_"," ")
 
  list(h4(strong(txt)),
       img(src=tt()$vcardImage[4]))
})



uiOutput("four")

```

### 5


```{r}

output$five <- renderUI({
 
 
  req(tt())
  
 txt <- str_replace_all(paste0(tt()$todayTopTen$article[5]," ",tt()$todayTopTen$views[5]," views"),"_"," ")
 
  list(h4(strong(txt)),
       img(src=tt()$vcardImage[5]))
})




uiOutput("five")

```


Row 
-----------------------------------------------------------------------

### 6

```{r}

output$six <- renderUI({
 
  
  req(tt())
  
  txt <- str_replace_all(paste0(tt()$todayTopTen$article[6]," ",tt()$todayTopTen$views[6]," views"),"_"," ")
 
  list(h4(strong(txt)),
       img(src=tt()$vcardImage[6]))
})




uiOutput("six")

```

### 7

```{r}

output$seven <- renderUI({
 
  
  req(tt())
  
  txt <- str_replace_all(paste0(tt()$todayTopTen$article[7]," ",tt()$todayTopTen$views[7]," views"),"_"," ")
 
  list(h4(strong(txt)),
       img(src=tt()$vcardImage[7]))
})




uiOutput("seven")

```

### 8

```{r}

output$eight <- renderUI({
 
  
  req(tt())
  
 txt <- str_replace_all(paste0(tt()$todayTopTen$article[8]," ",tt()$todayTopTen$views[8]," views"),"_"," ")
 
  list(h4(strong(txt)),
       img(src=tt()$vcardImage[8]))
})




uiOutput("eight")

```

### 9

```{r}

output$nine <- renderUI({
 
  
  req(tt())
  
  txt <- str_replace_all(paste0(tt()$todayTopTen$article[9]," ",tt()$todayTopTen$views[9]," views"),"_"," ")
 
  list(h4(strong(txt)),
       img(src=tt()$vcardImage[9]))
})




uiOutput("nine")

```

### 10

```{r}

output$ten <- renderUI({
 
  
  req(tt())
  
 txt <- str_replace_all(paste0(tt()$todayTopTen$article[10]," ",tt()$todayTopTen$views[10]," views"),"_"," ")
 
  list(h4(strong(txt)),
       img(src=tt()$vcardImage[10]))
})




uiOutput("ten")

```

